### ISSUE TITLE
Getting customer users list

### ISSUE THREAD

**Issue by Sodininkas** [PartnerCenterSamples/Reseller-Web-Application#13]
Hello,

I'm trying to get customers user list with line of code ApplicationDomain.Instance.PartnerCenterClient.Customers.ById(clientCustomerId).Users.GetAsync().But getting error "The supplied role does not have the rights to perform the requested operation" or "This resource can't be accessed by application credentials." reponse code 500. With native given "csp console sample app", it's working. But with web app i can't get users.

Thanks

**Comment by RaedJarrar** [comment]
An application only auth mode does not have enough privileges to access customer users. You should be getting back a 403 rather than a 500. Can you confirm this is the case? In order to access the customer users, you need to authenticate using app+user which would work with that. You can onboard a native app and use it to create a new partner credentials which would work.

**Comment by Sodininkas** [comment]
Hi,

Thanks yes this is the case! I also implemented user authentication, and now it's working i can get back users and other api features.

Thank you

**Comment by RaedJarrar** [comment]
Glad it worked out for you!
