### ISSUE TITLE
Bermuda Usage

### ISSUE THREAD

**Issue by coopersimpson** [PartnerCenterSamples/Reseller-Web-Application#14]
Hi,

When we tried to deploy for our LATAM reseller site, we get an issue straight away that saysCulture name 'BM' is not supported.
Parameter name: name

Here is the site MSFT generated for us.
https://fmreseller.azurewebsites.net/

Any advice? you can email me direct csimpson (at) fireminds.com

**Comment by tameemansari** [comment]
@coopersimpson our first release was targeting US primarily. We are investigating other countries for future releases. Can you tell me if PayPal is supported in your region.

**Comment by coopersimpson** [comment]
Hmm, very weird Microsoft would put this in the LATAM Partner portal then isn't it! :) Guess we will build somethign from scratch, or modify this. We use Credit card auth via AUthorize.net not paypal.

**Comment by tameemansari** [comment]
Thanks for the feedback. We encourage forking the code and introducing additional payment gateways and features beyond what we have been considering at our end. We would be glad to take PRs :). 

Meanwhile, there is an eminent release coming up (within a week) which will enable PayPal accounts as another funding instrument which will enable more partners to adopt in few other regions beyond US. Would suggest you wait till this goes out before you take a fork.

**Comment by ankbs** [comment]
Hallo  @tameemansari ,
in sugestion my other post..(#11 ).. you wrote "there is an eminent release coming up (within a week)" - is there a new date?

many thanks and best regards
michael

**Comment by tameemansari** [comment]
@ankbs ... The release is almost ready, we are undergoing tests to validate in place upgrade scenarios to allow partners who have deployed the store front from Partner Center to update to the new release. You can take a look at it in the [novrelease](https://github.com/PartnerCenterSamples/Reseller-Web-Application/tree/NovRelease) branch.

**Comment by ankbs** [comment]
Hello @tameemansari , thanks for your response.
i could change the Countgry list into my country. But the Change for the Customer phone don't work. i can't find  the second validation which is showing as Header bar.
buying new licenses and register a new client is working.
but the client can't login into the portal. the site is showing a green error site with the info "some error".
any idea?
and the last question. can you show me a sample Code how can i create a list of countries? sorry, but i'm not a developer ;-) thanks for your support.
best regards
michael

**Comment by tameemansari** [comment]
@ankbs. The customer phone validation is also done on the server side using a regular expression. You can remove the regex annotation in the [customer model class](https://github.com/PartnerCenterSamples/Reseller-Web-Application/blob/master/Source/PartnerCenter.CustomerPortal/Models/CustomerViewModel.cs#L95).  

Adding additional countries to the customer registration page will involve you adding items to the [select list viewModel variable](https://github.com/PartnerCenterSamples/Reseller-Web-Application/blob/master/Source/PartnerCenter.CustomerPortal/Scripts/Plugins/Views/NewCustomerProfileView.js#L18). You can see how multiple items are managed for such a page by taking a look at the [Payment type drop down behavior](https://github.com/PartnerCenterSamples/Reseller-Web-Application/blob/master/Source/PartnerCenter.CustomerPortal/Scripts/Plugins/PaymentSetupPresenter.js#L18)

Can you please post a gist with a screen shot for the customer login error you are seeing. 

Some of these things I am working on getting incorporated as part of the next release. Please share your insights so that we can triage and incorporate the right set of behaviors in to the store front code.

**Comment by tameemansari** [comment]
@coopersimpson . I did further digging into this issue and found that the code has a bug which cannot set the locale to Bermuda since .net framework doesn't have the locale support for it. We use this piece of logic to identify the currency settings we set for the web storefront. I am going to work on fixing this for our Dec/Jan release.

**Comment by tameemansari** [comment]
@coopersimpson and @ankbs. The dec/jan work stream is more or less complete. we are undergoing reviews internally after which relevant announcements and merge to master would happen. I hope this is done by end of next week. Meanwhile feel free to take a look at the [dev](https://github.com/PartnerCenterSamples/Reseller-Web-Application/tree/dev) branch.

**Comment by coopersimpson** [comment]
@tameemansari Thanks, look forward to merge. Did you get the Bermuda fix in place? As for currency settings, Bermuda could just force USD as a fix?

**Comment by tameemansari** [comment]
@coopersimpson . Yes Bermuda is fixed. Please look [here](https://github.com/PartnerCenterSamples/Reseller-Web-Application/blob/dev/Source/PartnerCenter.CustomerPortal/BusinessLogic/PortalLocalization.cs#L52-L70). Partner Center maintains a default culture setting for a given partner's locale (we retrieve this using the CountryValidationsRules api and accordingly set the currency & other region settings.).

If this fails then we setup en-US as the region for currency settings.

**Comment by coopersimpson** [comment]
Awesome, will deploy as soon as its Master and try it out!

Cooper Simpson
Fireminds Ltd.

Website: www.fireminds.com<http://www.fireminds.com/>
Email: csimpson@fireminds.com<mailto:csimpson@fireminds.com>
Direct: (441)278-1508
Help desk: (441)295-0000
Support: support@fireminds.com<mailto:support@fireminds.com>

**Comment by tameemansari** [comment]
The release is now out. Its on master and you can deploy the latest bits from partner center. 
https://github.com/PartnerCenterSamples/Reseller-Web-Application/releases/tag/v1.2
