### ISSUE TITLE
Getting Server Error

### ISSUE THREAD

**Issue by ns8482e** [PartnerCenterSamples/Reseller-Web-Application#15]
When I trying to run application in debug in Visual Studio 2015. I get following error.

Server Error in '/' Application.  

Unable to find account with tenant id 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' in AMS

I have setup integration sandbox in partner center, and updated config values for partnerCenter.applicationId, partnerCenter.applicationSecret, partnerCenter.AadTenantId , webPortal.clientId, webPortal.clientSecret, webPortal.AadTenantId from  Partner center "App Management" using App ID, Key, Account ID. 

I have set storage connection string for webPortal.azureStorageConnectionString  as UseDevelopmentStorage=true.

Am I missing any other configuration to set?

**Comment by tameemansari** [comment]
@ns8482e . I did further digging into this issue and found that the code has a bug which cannot set the locale to Bermuda since .net framework doesn't have the locale support for it. We use this piece of logic to identify the currency settings we set for the web storefront. I am going to work on fixing this for our Dec/Jan release.
