### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by lukeryb** [PartnerCenterSamples/Reseller-Web-Application#25]
Hi Team, 

We have a few elements that we are wondering if they can be added/removed. 

1. Could be eliminate the function of Paypal, and payment all together, as we would like to simply provide the end user the ability to add and remove licenses and subscriptions, without collecting payment. We manage billing externally. 

2. Second, the country option only allows for USA, how and can we select Canada. We currently only sell to the Canadian market, does that mean we can not on board new customers in Canada through this portal/store front. 

3. Lastly, is it possible to have current customers login, and view their existing subscriptions that weren't activated within the store front? 

Thanks.

**Comment by tameemansari** [comment]
Good list of features. 

- Removing Payment gateway to support offline payments & invoicing. 
We are looking at supporting this scenario for our Feb release. This capability will allow the web store front admin to pre approve customers so that they wouldn't be required to pay (the payment experience will be stubbed). We were considering to allow the admin to select which customers are pre approved. What you are asking is to support all the customers for the partner to be pre approved so that invoicing & payments can be done offline. Do note that we are considering to only support pre approval for pre existing customers. Collecting the payment will be mandatory in the **create customer & place first order** scenario. 

- Our Jan release will support Canada (and a whole lot of other countries) :). Its almost ready and undergoing internal reviews. You can take a look at the code [on the dev branch](https://github.com/PartnerCenterSamples/Reseller-Web-Application/tree/dev).

- Current customers (who are designated as global admins on the tenant) can login to the store front and **Yes with the Jan release** will be able to view all their license based subscriptions from the "My Subscriptions" page. The current "My Subscriptions" page is being renamed to "My Orders" which will allow customers to view their orders managed from the web store front. 

Can you drop me an email tansar [at] Microsoft.com so that we can review what we are considering in the pre approval scenario with you. Thanks.

**Comment by lukeryb** [comment]
Hi Tameemansari

I have sent you an email to the address in your reply. Looking forward to getting in contact with you. 

Thanks

**Comment by tameemansari** [comment]
@lukeryb. The jan release is now out. We are working on getting pre approved payments targeting the Feb release. Hope you can deploy the Jan release.  I will close this issue for now.
