### ISSUE TITLE
Increasing License Counts?

### ISSUE THREAD

**Issue by sean-anr** [PartnerCenterSamples/Reseller-Web-Application#35]
Correct me if I'm wrong, but do customers not have the ability to change their license counts on the _My Subscriptions_ page?  Mine is showing the correct license based subscription counts (and Ids), but no ability to add to it.

**Comment by tameemansari** [comment]
Customers may add update their subscriptions from the "My Orders" page.

**Comment by sean-anr** [comment]
I'm not seeing anything on the My Orders page for existing.  If I choice to purchase a new one I get this error: One or more offers you are trying to add already exists. You can add more licenses to existing subscriptions.

I see the existing subscriptions/license on the My Subscriptions page; which were added in the CSP portal.

Am I misunderstanding how this can be used?

**Comment by sean-anr** [comment]
![2017-02-27_11-35-03](https://cloud.githubusercontent.com/assets/14201019/23369918/eac79362-fce0-11e6-8eba-1675e12d087c.png)
![2017-02-27_11-35-18](https://cloud.githubusercontent.com/assets/14201019/23369919/eac9d654-fce0-11e6-9834-5baa9e27dc14.png)
Here is an example of what I'm seeing for a CSP customer.  Those are CSP licenses/subscriptions, but nothing can be changed.

**Comment by tameemansari** [comment]
@sean-anr. This behavior is by design. The My orders page allows a customer to manage any orders they have made from the storefront website. The My subscriptions page is primarily a way for the customer to get a complete view of all their subscriptions (License based and usage based in one place). 

There are quite a few reasons why these are distinct. Ultimately it boils down to the catalog of offers. The storefront website allows a partner to configure the storefront catalog (not the partner center catalog). The partner can configure their offer in a multitude of ways which the app saves locally (not dependent on partner center backend).

**Comment by sean-anr** [comment]
Should customers have the ability to decrease license counts on the My Orders page?

**Comment by sean-anr** [comment]
One other question, sorry for so many.  Billing, I just signed in with a client, added a license and it didn't ask me to pay?  That because they were pre-approved?

**Comment by tameemansari** [comment]
Customers cannot reduce the number of licenses from Chiron. 
Re. Pre-approved transactions yes. If this customer (or all customers) have been marked for pre approval then they will not be taken to the payment experience during the transaction.

**Comment by sean-anr** [comment]
Are the PayPal payment reoccurring?  I'm not seeing anything to that in the receipts.

**Comment by tameemansari** [comment]
Nope. PayPal payment processing is done on demand by redirecting user to the payment experience. It is not a recurring payment.

**Comment by sean-anr** [comment]
Thanks.
