### ISSUE TITLE
Error Validating Credentials

### ISSUE THREAD

**Issue by allanzh** [PartnerCenterSamples/Reseller-Web-Application#48]
I was trying to make your sample work, did all the steps found at your post on MSDN Blog but when i do the Deploy using Visual Studio returns an error page. 
![screenshot_1](https://user-images.githubusercontent.com/2539476/29786060-1971459c-8c00-11e7-9bec-0cb425257dd0.png)

Could you help me to fix it?

**Comment by allanzh** [comment]
Just to be clear: The debug process occurs perfectly, this error appears when i do the first access.

**Comment by isaiahwilliams** [comment]
Hi allanzh, this error message means you have specified an invalid secret key. In order to correct it you will need to double check that you have inserted the appropriate secret key value in the web.config. You can find the appropriate value in Partner Center by clicking on Dashboard -> Account Settings -> App Settings, and from there you can add a new secret key to the web app. When you copy it make sure there are not any leading, or trailing, spaces because that could cause this type of error as well.

**Comment by allanzh** [comment]
Hi @isaiahwilliams , first of all, thank you for spend time trying to help me out.
Following your tip, I've generated a new key on _Partner Center Sandbox_ and then remake the deployment process, with was a success, but in the first access the page shows another error.
![screenshot_1](https://user-images.githubusercontent.com/2539476/29878199-3f3c3326-8d78-11e7-9365-b4e0b756c20c.png)

**Comment by isaiahwilliams** [comment]
Hi @allanzh, thank you for sharing this information! This is an interesting error because according to the [documentation ](https://msdn.microsoft.com/en-us/library/partnercenter/mt634697.aspx) the operation to obtain the legal business profile requires app + user authentication. The reseller portal utilizes app only authentication when communicating with the Partner Center API, and I believe that is the root cause of this issue. Please give us some time to investigate and we will get back with you.

**Comment by allanzh** [comment]
Using Visual Studio on debug mode I could see that the error appears in the following part:

![screenshot_2](https://user-images.githubusercontent.com/2539476/29888073-ecb5f7ea-8d95-11e7-9ec3-407d2b8c6698.png)

So, I changed the ApplicationName and it works.

**Comment by allanzh** [comment]
@isaiahwilliams you can close this issue.
I already solved by generating newer secrets.
I don't know if this really matters, but I think you should recommend in your post to people change line: 
`PartnerService.Instance.ApplicationName = "Web Store Front V1.4"; `
to
`PartnerService.Instance.ApplicationName = "YourApplicationName";`

**Comment by tameemansari** [comment]
Thanks @isaiahwilliams.
