### ISSUE TITLE
Local Gateway

### ISSUE THREAD

**Issue by SplitView** [PartnerCenterSamples/Reseller-Web-Application#52]
Is it possible to add a local payment gateway of my country in the application?

**Comment by tameemansari** [comment]
Absolutely. We encourage you to fork the code and incorporate the changes to add your own payment gateway solution. We can assist in the implementation. 

@SplitView Can you share which country and what payment gateway are you looking to integrate.

**Comment by SplitView** [comment]
Thanks @tameemansari for reply. I am from Nepal and i want to integrate esewa as our gateway. the link to  docs is [here](https://1drv.ms/b/s!AhX7seYMjLvNgdIEWZwH4XaBFbUE5Q) . i hope you can help me on this

**Comment by ifeomai** [comment]
@tameemansari is there any documentation that can help with implementing a local gateway? My provider in NIgeria - Paystack `https://developers.paystack.co/` requires a callback url from their site, back into the application but I could not find one. Could you advise?

**Comment by ifeomai** [comment]
@tameemansari  is there any documentation that can help with implementing a local gateway? My provider in Nigeria - [Paystack](https://developers.paystack.co/) requires a callback url from their site, back into the application but I could not find one. Could you advise?

**Comment by ifeomai** [comment]
@SplitView where you able to implement your local gateway? How did you get that done?

**Comment by isaiahwilliams** [comment]
Hi @SplitView  and @ifeomai there are plans to refactor the invoicing feature in the near future to support monthly invoice. As part of that work we will be simplifying the process to add new payment gateways. I will be sure to include documentation on how to configure them. Since this work is planned for the near feature I am going to close this issue. Please feel free to reopen it if you have any quesitons.
