### ISSUE TITLE
Issue with Payment Gateway

### ISSUE THREAD

**Issue by Vijayaraghavanl** [PartnerCenterSamples/Reseller-Web-Application#9]
Hi Team,

I have a small request to you folks with regards to this code and wonder if you folks can help. 

Currently, this code allows only Paypal as the Payment Gateway. I am based out of India and under the CSP Program we can have only Indian customers. Unfortunately, I cannot use Paypal in India for transactions within India. Having said that though this code provides and includes everything that I may need or could think of the challenge with Payment Gateway is holding me up. Do you think you can help me with that? Or perhaps advise the sections of the code that will have to be changed so I can have my own payment gateway?

Any help is highly appreciated.

Thanks!
Vijayaraghavan

**Comment by RaedJarrar** [comment]
You can certainly implement your own IPaymentGateway which talks to one which is supported in India. You would need to hook it up to CommerceOperations to take effect instead of the PayPal one. Also, you would need to change your Payment configuration page to store your other provider's credentials instead of PayPal. Assuming that other GateWay supports creditcards, you should be up and running with these changes with no need to change the payment UX.

**Comment by tameemansari** [comment]
@Vijayaraghavanl can you share details of which payment provider you were considering for India. Thanks.

**Comment by Vijayaraghavanl** [comment]
Was considering CCAvenue.
